courses/urls.py
from django.urls import path, re_path
from . import views

app_name = 'courses'

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create_view'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit_view'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete_view'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(),name='module_content_create'), # content create
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),name='module_content_update'),# content update
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'), # content delete
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),


    # Displaying
    path('course/',views.CourseListView.as_view(), name='course_list_view'),
    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_list_subject'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail_view'),
    path('assignment/view', views.AssignmentListView.as_view(), name='assignment_list')



]

students/urls.py
from django.urls import path
from . import views

app_name = 'students_profile'

urlpatterns = [
    path('', views.StudentListProfileView.as_view(), name='student_profile_list'),
    path('profile/create/', views.register, name='student_profile_create'),
    path('profile/upload/', views.upload_student, name='student_profile_upload'),
    path('<int:pk>/profile/', views.StudentDetailProfileView.as_view(), name='student_profile_detail'),
    path('<int:pk>/update/', views.StudentUpdateProfileView.as_view(), name='student_profile_edit'),
    path('<int:pk>/profile/delete/', views.StudentDeleteProfileView.as_view(), name='student_profile_delete'),
    # Student Course Urls
    path('courses/', views.StudentCourseList.as_view(), name='student_course_list'),
    path('enroll/', views.student_enroll, name='student_enrollment'),
    path('courses/<pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail_view'),
    path('courses/<pk>/<module_id>/', views.StudentCourseDetailView.as_view(), name='student_course_module_detail_view'),
    path('create/enroll', views.CourseEnrollmentCreateView.as_view(), name='student_enroll_course')
]

courses/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse_lazy

from schools.models import DAYS_OF_WEEK, time_slots
from teachers.models import TeacherProfile
from .fields import OrderField

# Create your models here.

User = get_user_model()


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Subject(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, blank=True, null=True, help_text='Subject Code')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Course(models.Model):
    #id = models.CharField(primary_key='True', max_length=50)
    owner = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, related_name='courses_created')
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=300)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='courses')
    slug = models.SlugField(unique=True, blank=True, null=True, help_text='Course Code')
    shortname = models.CharField(max_length=50, default='X')
    students = models.ManyToManyField(User, related_name='courses_enrolled', blank=True)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)

    overview = RichTextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        default_permissions = ('add', 'change', 'delete')
        permissions = (
            ('can_enroll', 'Enroll In Course'),
        )

    def __str__(self):
        return "{} created by {}{}".format(self.title, self.name, self.owner)


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class CourseEnrollment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users_enrolled')

    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING, related_name='courses_enrolled')

    date_created = models.DateTimeField(auto_now_add=True, null=True, db_index=True)
    is_enrolled = models.BooleanField(default=True)

    def __str__(self):
        return self.course.students

    def get_absolute_url(self):
        return reverse_lazy("students_profile:student_profile_detail", args=[self.id])


class Assignment(models.Model):
    course = models.ForeignKey(Course, related_name='assignments', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    instruction = RichTextField()
    date_due = models.DateField()
    date_created = models.DateField(auto_now_add=True, null=True, db_index=True)
    date_updated = models.DateTimeField(auto_now=True)

    points_possible = models.IntegerField()

    CATEGORIES = {
        ('essay', "Essay"),
        ('test', "Test"),
        ('quiz', "Quiz"),
        ('ps', "Problem Set"),
        ('hwk', "Homework"),
        ('ec', "Extra Credit")
    }

    category = models.CharField(choices=CATEGORIES, max_length=20)

    def __str__(self):
        return "[" + self.get_assignment_category() + "] " + str(self.title) + ": " + str(self.instruction)

    def get_assignment_category(self):
        return dict(self.CATEGORIES).get(str(self.category))


class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = RichTextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)

    class Meta:
        ordering = ['order']


class Content(models.Model):
    module = models.ForeignKey(Module, related_name='contents', on_delete=models.CASCADE, limit_choices_to={
        'model__in': (
            'text',
            'video',
            'image',
            'file'
        )
    })
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, related_name='%(class)s_related')
    title = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('course/content/{}.html'.format(self._meta.model_name), {'item': self})


class Text(ItemBase):
    content = RichTextField()


class File(ItemBase):
    file = models.FileField(upload_to='courses/file/%Y/%m/%d')


class Image(ItemBase):
    file = models.FileField(upload_to='courses/images/%Y/%m/%d')


class Video(ItemBase):
    url = models.URLField()


class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='assigns')
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = TeacherProfile.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE, related_name='assign_time')
    period = models.CharField(max_length=50, choices=time_slots, default='10:49 - 11:29')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class CorporateHolidays(models.Model):
    school_holidays = models.DateTimeField()
    name = models.CharField(max_length=200)

students/forms.py
from django import forms
from django.forms import modelformset_factory
from courses.models import Course, CourseEnrollment
from courses.utils_mixins import CourseIDMixin
from students.models import StudentProfile


class StudentProfileCreateForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        exclude = ('date_created', 'date_updated', 'user')

    def save(self, commit=True):
        user = super(StudentProfileCreateForm, self).save(commit=False)
        if commit:
            user.student = True
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['other_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})

        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_admitted'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})


# Allows the selection of a single model object, suitable for representing a foreign key. Note that the default widget
# for ModelChoiceField becomes impractical when the number of entries increases.
# You should avoid using it for more than 100 items.
#
# A single argument is required:

class CourseEnrollmentForm(forms.ModelForm, CourseIDMixin):

    def get_queryset(self, courses, user):
        courses = forms.ModelChoiceField(widget=forms.CheckboxSelectMultiple,
                                     queryset=Course.objects.filter(pk=self.kwargs['crs']))
        users = forms.ModelChoiceField(widget=forms.CheckboxSelectMultiple,
                                      queryset=StudentProfile.objects.all())
        return self.get_queryset(self, courses, user)

    class Meta:
        model = CourseEnrollment
        fields = ['course', 'user']


CourseEnrollmentFormSet = modelformset_factory(CourseEnrollment, exclude=('date_created',))

students/templates/students/course/detail.html
{% extends 'index.html' %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {{ object.title }}
    </title>
</head>
{% block content %}
<div class="main-content-inner">
<div class="row">
<div class="col-lg-8 col-ml-12">

    {% with course=module.course %}
    <div class="course-heading pt-5">
        <h3>Course  "{{ course.title }}"</h3>
        <hr />
    </div>

        <div class="content">
         <ul>
         {% for m in object.modules.all %}
             <li data-id="{{ m.id }}" {% if m == module %} class="selected" {%endif %}>
               <a href="{% url 'students_profile:student_course_module_detail_view'  object.pk m.id %} ">
                    <span> <h3>{{ m.title }}</h3>  </span>
             </a>
              </li>
             {% empty %}
             <li>No Modules Yet</li>
            {% endfor %}
          </ul>
          <h3>Modules</h3>
                {% for content in module.contents.all %}
                Module {{ module.id }}
                {% with item=content.item %}
                <h2>{{ item.title }}</h2>
                    {{ item.render }}
                  {% endwith %}
                 {% endfor %}
        </div>
 {% endwith %}
</div>
</div>
</div>
   {% endblock %}

students/templates/students/course/enroll_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %} {{ block.super }} | Edit Content {% endblock %}
{% block content %}

<div class="main-content-inner">
  <div class="row">
     <div class="col-lg-6 col-ml-12">
        <div class="row">
          <div class="col-12 mt-5">
              <div class="module">

                    {% if request.user.is_authenticated %}
                        <h2>Class Enrollment</h2>
                        <form action="{% url 'students_profile:enroll_student_course' %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" value="Enroll in Class">
                        </form>
                    {% endif %}
              </div>

         </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

students/templates/students/course/list.html
{% extends 'index.html' %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Courses</title>
</head>
{% block content %}
 <div class="main-content-inner">
    <div class="row">
        <div class="col-lg-9 col-ml-12">
            <div class="row">
                <div class="col-12 mt-5">

    <div class="module">

         {% for course in courseenrollment_list %}
            <div class="course-info">
                <h3>{{ course.title }}</h3>
                <p><a href="{% url 'students_profile:student_course_detail_view' course.course_id %}">Access Contents</a></p>
            </div>
            {% empty %}
            <p>
                You are not enrolled in any courses yet.
                <a href="{% url 'courses:course_list_view' %}">Browse courses</a>
                to enroll in a course.
            </p>
        {% endfor %} 
    </div>
                </div>
            </div>
        </div>
    </div>
 </div>

{% endblock %}